---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: account-example
    name: account-example
    namespace: default
spec:
    ports:
        - name: "http"
          protocol: TCP
          port: 8083
          targetPort: 8083
    selector:
        App: backend
status:
    loadBalancer: {}
  